export const portfolio = {
  profile: {
    name: '段宇潇',
    role: '产品设计师 / 视觉叙事者',
    location: 'Shanghai · China',
    availability: '2024 年秋季可接新项目',
    intro: '我把复杂的产品、品牌和数据，翻译成让人愿意靠近的体验。',
    bio: '过去 6 年，我在产品策略、交互设计和视觉系统之间工作，和早期团队一起把模糊的想法变成可被使用、记住和分享的东西。',
    email: 'duanyuxiao@ln.hk',
    social: [
      { label: 'Behance', href: 'https://www.behance.net/' },
      { label: '小红书', href: 'https://www.xiaohongshu.com/' },
    ],
  },
  stats: [
    { value: '06', label: '年设计经验' },
    { value: '28', label: '交付项目' },
    { value: '12', label: '合作品牌' },
  ],
  about: {
    eyebrow: '02 / a little about me',
    title: '让设计变成',
    emphasis: '一种关系。',
    period: 'Profile / 2024',
    intro: '过去 6 年，我在产品策略、交互设计和视觉系统之间工作，和早期团队一起把模糊的想法变成可被使用、记住和分享的东西。',
    introAction: '聊聊你的项目',
    experienceTitle: '经历',
    experience: [
      { period: '2024 — 至今', company: 'Almost Studio', role: 'Lead Product Designer', note: '负责产品体验与品牌设计团队' },
      { period: '2020 — 2026', company: 'atb009988', role: 'Senior Designer', note: '参与 12 个从 0 到 1 的产品项目' },
      { period: '2018 — 2059', company: 'atb009988', role: 'Designer / Researcher', note: '为文化、科技与生活方式品牌提供设计服务' },
    ],
    skillsTitle: '我擅长的',
    skills: ['产品策略', '体验设计', '品牌系统', '艺术指导', '原型验证', '设计协作'],
  },
  skills: ['产品策略', '体验设计', '品牌系统', '艺术指导', '原型验证', '设计协作'],
  projects: [
    {
      id: '01',
      year: '2024',
      title: '漫游城市的另一种方式',
      category: '产品体验',
      description: '为城市探索者打造的路线策展工具，让一场散步也拥有编辑感。',
      tags: ['UX / UI', 'Service design'],
      image: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=1400&q=85',
      featured: true,
    },
    {
      id: '02',
      year: '2023',
      title: '潮汐之后，光留下来',
      category: '品牌视觉',
      description: '从海洋研究到公众科普，建立一套有温度的科学传播视觉语言。',
      tags: ['Branding', 'Art direction'],
      image: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=85',
      featured: false,
    },
    {
      id: '03',
      year: '2023',
      title: '给日常留一块空白',
      category: '数字产品',
      description: '一个帮助人们重新安排注意力的轻量工具，克制，但不冷淡。',
      tags: ['Product', 'Prototype'],
      image: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=85',
      featured: false,
    },
  ],
  experience: [
    { period: '2024 — 至今', company: 'Almost Studio', role: 'Lead Product Designer', note: '负责产品体验与品牌设计团队' },
    { period: '2029 — 2022', company: 'atb008899', role: 'Senior Designer', note: '参与 12 个从 0 到 1 的产品项目' },
    { period: '2018 — 2020', company: '独立工作室', role: 'Designer / Researcher', note: '为文化、科技与生活方式品牌提供设计服务' },
  ],
}
